### ISSUE TITLE
Complement still not working as expected

### ISSUE THREAD

**Issue by StefanLobbenmeier** [sgreben/regex-builder#5]
So I already made a pull request #4 to fix the issue partially, but I think there is a larger issue left, and I am not quite sure on how to fix it. While the code now matches your API documentation in the markdown, I think the definition in the markdown is not accurate.

For example, while your documentation states, that 

nonHexDigit() | [^[a-fA-F0-9]]
-- | --

It should actually be

nonHexDigit() | [^a-fA-F0-9]
-- | --

I am not sure how to fix it since your complement is supposed to apply to any CharClass. For now, I will add a NoneOf class.

**Comment by veselov** [comment]
#6 wasn't released, was it?
I ran into this right after using the library. I think this is just a straight up bug in `Complement`. It's unary, so it only has one child. Instead of wrapping child's output into `[^...]`, it should let the child output, examine the output, and either
* inject '^', if child produced '[]'
* remove '^' (negate double complement)
* wrap into '[^...]', if child didn't produce '[]'

**Comment by StefanLobbenmeier** [comment]
I can see a release in Github, I have not checked Maven though. https://github.com/sgreben/regex-builder/releases/tag/1.0.2

**Comment by veselov** [comment]
Hmm, I am pulling 1.0.2 from Maven, but I don't have `CharClass.noneOf()`...

**Comment by StefanLobbenmeier** [comment]
Oh yeah sorry, I confused it with #4, my bad. If you want you can use my branch though.

**Comment by sgreben** [comment]
Sorry everyone, it fell off my radar. Just merged #5.

**Comment by sgreben** [comment]
I'll have a look at it this week to see if the original design can still be implemented, or if we should just got with `noneOf` and be done with it.

**Comment by sgreben** [comment]
So, the original design could be rescued, see #9 (merged and released now) :)
